### PR TITLE
2013 SS Model

### PR DESCRIPTION
**Pull request by Ovec8hkin**
The 2013 SS model works using SS v. 3.24U (the closest executable I could find to exactly what was used in 2013). 
Also updates the `.gitignore` to not track some of the SS output files.

### CODE REVIEW

**Review by MatthVeron — CHANGES_REQUESTED** [review]
1- [2013 model working with SS3.24U](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/pull/10/commits/4fd82fa16c53f57076d343e6b7a039d827b47824)
I wonder if we really need to upload all of this. I was thinking about maybe uploading the main input and output files, the .exe's and most importantly, checking out all of these functions because there are a bunch of things that (personally) I haven't checked out so maybe it would be nice to see what they're really for.

2- [Update .gitignore to not track ADMB binary file outputs](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/pull/10/commits/fc3efcb1ad84dd99c485db6421020ea6e1a57dd8)
I would also add the following (which are specific to SS and ADMB and that we don't really need on git):
`*.bar`, `*.eva`, `*.cor`, `*.std`, `*.ss_new`, `posterior_vector.sso`, `posterior.sso`, `rebuild.sso`, `runnumber.ss`

**Comment by JaneSullivan-NOAA** [comment]
Hey @Ovec8hkin and @MatthVeron I'm going to be unavailable for the next couple of days. Once you all are happy with a framework, I will accept/merge the PR. Thank you, and just quickly looking, awesome work! Way to get this running.

**Comment by Ovec8hkin** [comment]
@MatthVeron take another look. I removed a lot of the extra R files from the original 2013 assessment, and added the the files you recommended to the .gitignore.

**Review by MatthVeron — APPROVED** [review]
That sounds perfect to me. I think we can merge the branch to the main so people can have a "real" look at it. I'll make a pull request for the model running with the new version later today ! 
Thanks @Ovec8hkin for this !!!

**Pull request merged**
