### PR TITLE
Transitioning SST 2013 model from V324 to V330

### PR DESCRIPTION
**Pull request by MatthVeron**
# SST 2013 model using SS V3.30.21

## Scripts for the transition

All scripts used for the transition are in the folder [`Script_comp_versions`](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/2013_bridge/model/2013_SST_SSV3_30_21/Script_comp_versions) and include:

* the [Transition_SST_From_V324_To_V330.R](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/2013_bridge/model/2013_SST_SSV3_30_21/Script_comp_versions/Transition_SST_From_V324_To_V330.R) which realize the transition for all input files with notes and explanations about choices made (maybe this one needs to be divided in several script for each files)
* the [Plot_comparisons_V324_V330.R](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/2013_bridge/model/2013_SST_SSV3_30_21/Script_comp_versions/Plot_comparisons_V324_V330.R) which realize the comparison between the two SS versions (plots in pdf format)

## Executables

I created a folder [`Executables`](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/2013_bridge/Executables) in the root of the repo. It contains the `.exe` for each version of SS and for the different OS. These `.exe` are directly call from the R script when needed so we don't need to copy them in the folder of the run

## New functions

I created two functions () in the [`clean_functions`.R](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/2013_bridge/R/utils/clean_functions.R) that allow to clean the outputs from SS and only keep the files we are interested in to get on github. (@Ovec8hkin this is in addition to the .gitignore I don't know if that a good idea but I felt it could be useful)

## The transition

* The transition is based on a pre-existing model download from the SS3 Vlab website. The files from this model are stored in the [`base_model_example`](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/2013_bridge/model/2013_SST_SSV3_30_21/base_model_example) folder and are used in the script used for the transition.
* The new input files for the V3.30 version are stored in the [`2013_SST_SSV3_30_21`](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/2013_bridge/model/2013_SST_SSV3_30_21) folder and are used in the [`run`](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/2013_bridge/model/2013_SST_SSV3_30_21/run) folder to run the assessment. You will find the outputs from the assessment in that folder.
* The results of the comparison are in the [SSplotComparisons_15-Feb-2023_16.47.pdf](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/2013_bridge/model/2013_SST_SSV3_30_21/SSplotComparisons_15-Feb-2023_16.47.pdf) file. There are pretty cool I guess !!

### CODE REVIEW

**Comment by Ovec8hkin** [comment]
Thanks for doing this @MatthVeron. I will take a look at it carefully later tonight or tomorrow.

**Comment by Ovec8hkin** [comment]
@MatthVeron The transition script looks fine to me (presumably we won't need to run it again, so Im not terribly concerned with its structure, just that it works). 

I have some thoughts on generalizing the code in the `Plot_comparisons...` file. I would, ideally, like to make that an example of how we want to run SS models in the future. Mind if I make and add changes?

**Comment by MatthVeron** [comment]
@Ovec8hkin Of course go for it. That was just a quick script to get the plots and I was thinking to add stuff to compare likelihoods and derived quantities (e.g., manaement reference points) because that's probably something we will be asked for. 
Also I didn't have in mind that this script would be used as an exemple for running SS, I thought it was different but as you want ;)

**Comment by Ovec8hkin** [comment]
@MatthVeron Im running into a problem running the `Plot_comparisons...` function. the `r4ss::run(...)` command is throwing the following error: 

`Error in check_exe(dir = dir, exe = exe, verbose = verbose) : 
  /Users/jzahner/Desktop/Projects/shortspine_thornyhead_2023/Executables/SS_V3_24_U/SSv3.24U_Win64/SS3safe not found in /Users/jzahner/Desktop/Projects/shortspine_thornyhead_2023/model/2013_SST/base_model_files nor in the path.`

As far as I can tell, the `run()` command doesn't like being passed a full path to the desired SS executable, and instead attempts to look for the SS executable by name (as specified by the `exe` parameter) in the model directory (as specified by the `dir` parameter). Can you confirm whether this is also the case for you, or if this is a Mac specific problem?

If this is the case, the simplest thing to do would be to identify the desired SS executable and just run `file.coy()` and move it to the SS model directory.

**Comment by MatthVeron** [comment]
@Ovec8hkin I think this is a Mac specific problem because it works on windows. And checking the check_exe() function from R4ss you should be able to specify the directory where to find the `.exe` as long as you give the name of the `.exe` you want to use.

**Comment by Ovec8hkin** [comment]
@sowasser That did it. Thanks.

**Comment by Ovec8hkin** [comment]
@MatthVeron @JaneSullivan-NOAA Make some small updates to the file structure. Can someone verify that everything still works, and I didn't miss committing anything?

**Comment by Ovec8hkin** [comment]
I messed something up. Will fix tomorrow.

**Comment by MatthVeron** [comment]
Thanks for this @Ovec8hkin. Some few things that should be "changed" to me:
- We should keep only 1 `ss_executable` folder to avoid any confusion in the future (so removing either the one on the root or the one in the `model` folder)
- it seems that the `run` folder for the 3.30 SS version disapear from github.. Did I miss something?
- I think it should be easier for the user to automatically detect the OS in the `get.ss.exe.path` function (`ifelse(isWindowsOS(),yes = ...., no=...)`) and just stop everything if the exe is not available for the OS sending a warning asking the user to download the `exe` and house it in the `ss_executable` folder
- It seems that we still have all the output files for the 2013_SST model (something wrong in the .gitignore? - I'll check this) - There is the `clean_bat` function that can help after each run
- Do we need to get all the plots on github (2013_SST model)? I think it should be easier to just let people to plot the outputs by themselves

I can takkle all of this if you want me to!

**Comment by Ovec8hkin** [comment]
@MatthVeron Generally I agree with all of these. I messed up the 2013 model and panic pushed it back, so I wasn't being careful about what was pushed. I will clean it up later today. Thanks for your thoughts.

**Comment by Ovec8hkin** [comment]
@MatthVeron 

> I think it should be easier for the user to automatically detect the OS in the get.ss.exe.path function (ifelse(isWindowsOS(),yes = ...., no=...)) and just stop everything if the exe is not available for the OS sending a warning asking the user to download the exe and house it in the ss_executable folder

Generally, I agree that this is desirable. The hangup is that there's not a simple way to test if the windows OS is 32-bit or 64-bit, which is needed to select the proper executable for SS v3.21.U. If you know of a way to identify this reliably, I will happily make this change.

**Comment by MatthVeron** [comment]
@Ovec8hkin 

>Generally, I agree that this is desirable. The hangup is that there's not a simple way to test if the windows OS is 32-bit or 64-bit, which is needed to select the proper executable for SS v3.21.U. If you know of a way to identify this reliably, I will happily make this change.

I tihnk you can use the following command `Sys.info()[["machine"]]` that will give you either `x86_32` (32-bit) or `x86_64` (64-bit) ;)

**Comment by Ovec8hkin** [comment]
@MatthVeron I think this is done. Want to check everything works for you?

**Comment by MatthVeron** [comment]
Thanks @Ovec8hkin .

Just a question, you did not want to keep the `Run` folder? I thought that might be great to get the `original` input files housed in the root and then copy and paste them in the `Run` folder just in case modifications are made for the run we still have the `original ones`. I think it can be useful to test different version of a model structure when we just modify the estimation of something for example. As you want. 

Otherwise, that's OK for me !

**Comment by Ovec8hkin** [comment]
That's a good point. I added the run directory back in.

**Pull request merged**
